/**
 * Build static dictionary files from tokenizer JSON files.
 *
 * This script reads tokenizer files, applies filters, and generates
 * TypeScript files with static token arrays in src/dictionaries/.
 *
 * Usage: pnpm build:dictionaries
 */

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

import { loadTokens, type ModelId } from './lib/tokenizers.js';
import { createAllowFilter, type AllowOptions } from '../src/filter.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const ROOT_DIR = path.resolve(__dirname, '..');
const OUTPUT_DIR = path.join(ROOT_DIR, 'src', 'dictionaries');

// ============================================================================
// Dictionary Definitions
// ============================================================================

interface DictionaryConfig {
  /** Output filename (without extension) */
  name: string;
  /** Source tokenizer model */
  model: ModelId;
  /** Filter options */
  filter: AllowOptions;
  /** Optional: max number of tokens */
  limit?: number;
  /** Description for the export comment */
  description: string;
}

const DICTIONARIES: DictionaryConfig[] = [
  {
    name: 'gpt-4o',
    model: 'gpt-4o',
    filter: { whitespace: false },
    description:
      'GPT-4o vocabulary - full tokenizer vocabulary filtered for printable tokens.',
  },
  {
    name: 'claude',
    model: 'claude',
    filter: { whitespace: false },
    description:
      'Claude vocabulary - full tokenizer vocabulary filtered for printable tokens.',
  },
  {
    name: 'llama-4',
    model: 'llama-4',
    filter: { whitespace: false },
    description:
      'Llama 4 vocabulary - full tokenizer vocabulary filtered for printable tokens.',
  },
  {
    name: 'lowercase-alphanumeric',
    model: 'gpt-4o',
    filter: {
      uppercase: false,
      unicode: false,
      punctuation: false,
      whitespace: false,
      numbers: true,
    },
    description:
      'Lowercase alphanumeric vocabulary from GPT-4o. Tokens containing only lowercase letters and digits.',
  },
  {
    name: 'alphanumeric',
    model: 'gpt-4o',
    filter: {
      unicode: false,
      punctuation: false,
      whitespace: false,
      numbers: true,
      uppercase: true,
    },
    description:
      'Alphanumeric vocabulary from GPT-4o. Tokens containing only ASCII letters and digits.',
  },
];

// ============================================================================
// Code Generation
// ============================================================================

function escapeStringForTS(str: string): string {
  return str
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "\\'")
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    .replace(/\t/g, '\\t');
}

function generateDictionaryFile(tokens: string[], config: DictionaryConfig): string {
  const lines: string[] = [
    '// Auto-generated by scripts/build-dictionaries.ts',
    '// Do not edit manually',
    '',
    '/**',
    ` * ${config.description}`,
    ` * ${tokens.length.toLocaleString()} tokens`,
    ' */',
    `export const tokens: string[] = [`,
  ];

  // Write tokens in chunks for readability
  const TOKENS_PER_LINE = 1;
  for (let i = 0; i < tokens.length; i += TOKENS_PER_LINE) {
    const chunk = tokens.slice(i, i + TOKENS_PER_LINE);
    const tokenStrings = chunk.map((t) => `'${escapeStringForTS(t)}'`).join(', ');
    lines.push(`  ${tokenStrings},`);
  }

  lines.push('];');
  lines.push('');

  return lines.join('\n');
}

function generateIndexFile(dictionaries: DictionaryConfig[]): string {
  const lines: string[] = [
    '// Auto-generated by scripts/build-dictionaries.ts',
    '// Do not edit manually',
    '',
    '// Re-export all dictionaries',
  ];

  for (const config of dictionaries) {
    const exportName = config.name.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
    lines.push(
      `export { tokens as ${exportName} } from './${config.name}.js';`
    );
  }

  // Add aliases using the same tokens export
  lines.push('');
  lines.push('// Aliases for convenience');
  lines.push('export { tokens as lowercaseStandard } from \'./lowercase-alphanumeric.js\';');
  lines.push('export { tokens as gpt4oVocab } from \'./gpt-4o.js\';');
  lines.push('export { tokens as claudeVocab } from \'./claude.js\';');
  lines.push('');

  return lines.join('\n');
}

// ============================================================================
// Main
// ============================================================================

async function main() {
  console.log('Building dictionaries...\n');

  // Ensure output directory exists
  if (!fs.existsSync(OUTPUT_DIR)) {
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });
  }

  const stats: { name: string; count: number; size: number }[] = [];

  for (const config of DICTIONARIES) {
    // Load and filter tokens
    let allTokens: string[];
    try {
      allTokens = loadTokens(config.model);
    } catch {
      console.error(`  ✗ ${config.name}: tokenizer not found (${config.model}.json)`);
      continue;
    }

    const filter = createAllowFilter(config.filter);
    // Filter out empty tokens and apply allow filter
    let tokens = allTokens.filter((t) => t.length > 0 && filter(t));

    // Apply limit if specified
    if (config.limit && tokens.length > config.limit) {
      tokens = tokens.slice(0, config.limit);
    }

    // Generate and write file
    const content = generateDictionaryFile(tokens, config);
    const outputPath = path.join(OUTPUT_DIR, `${config.name}.ts`);
    fs.writeFileSync(outputPath, content);

    const sizeKb = (Buffer.byteLength(content) / 1024).toFixed(1);
    stats.push({ name: config.name, count: tokens.length, size: Buffer.byteLength(content) });
    console.log(`  ✓ ${config.name}: ${tokens.length.toLocaleString()} tokens (${sizeKb} KB)`);
  }

  // Generate index file
  const indexContent = generateIndexFile(DICTIONARIES);
  const indexPath = path.join(OUTPUT_DIR, 'index.ts');
  fs.writeFileSync(indexPath, indexContent);
  console.log(`  ✓ index.ts`);

  // Summary
  const totalTokens = stats.reduce((sum, s) => sum + s.count, 0);
  const totalSize = stats.reduce((sum, s) => sum + s.size, 0);
  console.log(`\nTotal: ${totalTokens.toLocaleString()} tokens, ${(totalSize / 1024).toFixed(1)} KB`);
}

main().catch(console.error);
